- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"