- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"